### ISSUE TITLE
Autocomplete does not show up

### ISSUE THREAD

**Issue by azmy60** [jcha0713/cmp-tw2css#1]
Somehow the autocomplete doesn't work, but `:CmpStatus` shows that it's ready.
![image](https://user-images.githubusercontent.com/38707148/190854568-b9fb76ef-e726-4954-9b3b-bf6e047c5335.png)

Tested on nvim 0.7.2

**Comment by jcha0713** [comment]
Hi, thanks for submitting this issue.

I want to first check if other source engines for cmp are working and it's only the `cmp-tw2css` that is not working.
Also `cmp-tw2css` does its job only when the cursor is in the css code block. Could you verify that it's still not working inside the css block?

**Comment by azmy60** [comment]
Thanks for your reply. Yes, I just tested it with a minimum configuration. In this one, I added cssls lsp to check if the other source is working.

<details>
<summary>init.lua</summary>

```lua
vim.cmd [[packadd packer.nvim]]

require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'neovim/nvim-lspconfig'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'L3MON4D3/LuaSnip'
  use 'saadparwaiz1/cmp_luasnip'
  use { 'hrsh7th/nvim-cmp', requires = 'jcha0713/cmp-tw2css' }
end)

vim.opt.completeopt = {"menu", "menuone", "noselect"}

local cmp = require'cmp'
cmp.setup({
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
    end,
  },
  window = {},
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  }),
  sources = cmp.config.sources({
    { name = 'luasnip' }, -- For luasnip users.
    { name = 'nvim_lsp' },
    { name = 'cmp-tw2css' },
  })
})

local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
local lspconfig = require('lspconfig')
lspconfig.cssls.setup {
  capabilities = capabilities,
}
```

</details>

![Peek 2022-09-19 01-32](https://user-images.githubusercontent.com/38707148/190923011-524485c0-5faf-4319-86e2-43879e3f6389.gif)

**Comment by jcha0713** [comment]
Hey, thank you for providing the minimum config and sorry for the delay.

I used your `init.lua` and almost reimplemented my plugin from scratch to make sure we're dealing with the same error.
It turns out that you might be missing the css parser for treesitter. You can install it using `:TSInstall css` command.
Try this and let me know if this solves your issue.

**Comment by azmy60** [comment]
Hmm... It's still not working, unfortunately. I tried to reinstall neovim from clean start and run `:TSInstall css` but still get the same result. I will try this again on a different machine and keep you updated.

**Comment by jcha0713** [comment]
Hmm.. that's odd. Can you make sure you have `nvim-treesitter` installed in your neovim?

**Comment by azmy60** [comment]
Yes, I've updated my config to use nvim-treesitter.

**Comment by azmy60** [comment]
Suddenly, I can see the auto completion working. I didn't try to fix it and don't know what happened lol. Probably cause the update? Anyway, thanks for making this plugin!
